language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run test
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov
