title: 'Vuex-ORM Apollo Plugin'
description: 'Vue + Vuex-ORM + GraphQL = <3'

base: '/vuex-orm-apollo/'

themeConfig:
  nav:
    - text: Home
      link: /

    - text: Guide
      link: /guide/

    - text: Vuex-ORM
      link: https://vuex-orm.github.io/vuex-orm/

    - text: GitHub
      link: https://github.com/vuex-orm/vuex-orm-apollo

  sidebar:
    - ['/guide/', 'Introduction']
    - /guide/setup/
    - /guide/graphql/
    - /guide/fetch/
    - /guide/persist/
    - /guide/push/
    - /guide/destroy/
    - /guide/custom-queries/
    - /guide/custom-mutations/
    - /guide/relationships/
    - /guide/eager-loading/
    - /guide/virtual-fields/
    - /guide/meta-fields/
    - /guide/faq/
